### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by pablrod** [pablrod/p5-Alien-XGBoost#2]
XGBoost works on windows (see: https://ci.appveyor.com/project/tqchen/xgboost). It's using MSVC but at least this package should support [Strawberry Perl](http://strawberryperl.com/)

**Comment by plicease** [comment]
Please let me know if I can help out here, I did quite a bit of work to get the CMake plugin (that you are using) working on with the various flavors of Perl on windows (including Strawberry).

**Comment by pablrod** [comment]
Thanks again!!

The problem is executing cmake:
```
Alien::Build::CommandSequence> + cmake -G MinGW Makefiles .
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
external command failed at C:/strawberry/perl/site/lib/Alien/Build/CommandSequence.pm line 49.
```
I'm testing this with Strawberry Perl 5.24.0 64bits PDL edition where `dmake` is available. It's my windows box, so I can change and install another version.

If you need more info, just let me know!

**Comment by plicease** [comment]
I think what you need is to add `-DCMAKE_MAKE_PROGRAM:PATH=%{make}` to the cmake call.  Unfortunately cmake does not support dmake, but I think Strawberry also comes with gmake, and the plugin should be able to find that and set %{make} appropriately.  You can also use `@{ meta->prop->{plugin_build_cmake}->{args} },` to get the flags that the plugin thinks you should use (see the perldoc, it has been updated with version 1.00 I think).

**Comment by pablrod** [comment]
Yes!! Adding `-DCMAKE_MAKE_PROGRAM:PATH=%{make}` cmake works perfectly!
And I prefer to use `@{ meta->prop->{plugin_build_cmake}->{args} }`. Thanks!!

Now the problem is that XGBoost's cmake doesn't provide install target. So I had to resort to do a "manual" install (even disable `destdir`). I mean these lines in the `alienfile`:
```perl
        'mkdir -p %{.install.stage}/dynamic',
        'mkdir -p %{.install.stage}/bin',
        ['%{cp}', 'lib/libxgboost.so', '%{.install.stage}/dynamic/'],
        ['%{cp}', $command, '%{.install.stage}/bin/'],
    ];
    meta_prop->{destdir} = 0;
```
And at least `libxgboost.so` is not very portable. But it's the `-p` option with mkdir that breaks the installation.

**Comment by plicease** [comment]
I think you can do `lib/libxgboost.*`.  I am open to adding a %{mkdir_p} helper, though I am not sure about the name.  It may be easier to write the install steps as a code reference using `Path::Tiny`, as that will be more portable.

**Comment by pablrod** [comment]
In windows it's only `xgboost.dll` but I think I can handle using `lib/*xgboost.*`. 
I agree with you that using `Path::Tiny` will be more portable.

I'm testing using `Path::Tiny`:
```perl
sub {
        my ($build) = @_; 
        path($build->install_prop->{stage}, 'dynamic')->mkpath;
        path($build->install_prop->{stage}, 'bin')->mkpath;
    },
```
But now the problem is with linux: cp helper doesn't like wildcards. It says:
```
Alien::Build::CommandSequence> + cp lib/*xgboost.* /tmp/LeU1BC2BkD/dynamic/
cp: cannot stat ‘lib/*xgboost.*’: No such file or directory
```
Using `af` I can stop after that and using `cp` in the shell works perfectly.

**Comment by pablrod** [comment]
I can use `$Config{so}` for extension, but the `lib` prefix I don't know a portable way to get it.
The only way I know is making something like:  
```perl
my $libprefix = $^O ne 'MSWin32' ? 'lib' : '';
```

**Comment by plicease** [comment]
I recommend using FFI::CheckLib (again in a  code ref) to find and copy the dynamic libs.

```perl
path($_)->copy(path($build->install_prop->{stage})->child("lib/$_")) 
  for FFI::CheckLib::find_lib( libpath => 'lib', name => '*' );
```

(caveat code is totally untested, and usage might not quite be right).  The logic for finding dynamic libraries is complicated:  https://metacpan.org/source/PLICEASE/FFI-CheckLib-0.16/lib/FFI/CheckLib.pm#L41

which is why I wrote the module :)

**Comment by pablrod** [comment]
Oh! Great! Substantially better than my solution!! Thanks!!
I'm testing it!

**Comment by pablrod** [comment]
Build process now works perfect in Windows!!
Although test pass, windows report a segmentation fault in perl.exe. It seems like everything works ok, but I have to double check this before claiming that this works on windows

**Comment by plicease** [comment]
fyi- I've added %{mkdir_deep} in 1.04.  It is `mkdir -p` on unix and `md` on windows (which does the same thing as `mkdir -p`).  May need to put the path in double quotes for md ie `%{mkdir_deep} "%{.install.stage}/dynamic"`.

**Comment by pablrod** [comment]
Oh! Thanks! I'm going to give it a try!

**Comment by pablrod** [comment]
In windows I can't call `XGBGestLastError` without a previous `XGBoost` call and this exactly what I'm doing in `t/10-dynamic_lib_xgboost.t`. 
I'm going to use another function call.

**Comment by pablrod** [comment]
All fixed! And I'm using the new helper `%{mkdir_deep}`! Thanks @plicease !!
